version: '3.8'
services:
  shop:
    build: .
    container_name: musicshop
    volumes:
      - .:/musicshop
  shop_migrate:
    extends:
      service: shop
    container_name: 'shop_migrate'
    command: >
      /bin/sh -c "python3 manage.py migrate --force-color -v 3
      && python3 manage.py loaddata user/fixtures/user.json cart/fixtures/cart.json product/fixtures/product.json"
  shop_run:
    extends:
      service: shop_migrate
    container_name: 'shop_run'
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:7000
    ports:
      - 7000:7000
