# Generated by Django 3.2.7 on 2022-07-12 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220712_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Значение'),
        ),
    ]
